=  Chairpersons Blog
:hp-tags: perth masters, swimming, chairpersons blog,

== Hello to all swimmers!!

I hope everyone survived April fool’s day without too many dramas =]

I’m writing ‘April’s Chinwag’, to let you all know of the progress
that we’ve made since our AGM which was held at the end of February.

First of all, here’s just a wee reminder of the fab Committee Members
and their jobs- These guys put in so much time and effort to make our
club run smoothly…..

> Treasurer- ANDY SANWELL

> Secretary/membership- TRUDY TORRIE

> Events- ANDREW BAILEY

> Website Designer/Tech Guru- KYRAN MCMANUS

> Coaches- RODDY MCCALL/ERIN TORRIE


Round of applause to all of you listed above!!!



*MEMBERSHIP*

I hope everyone has received and replied to Trudy’s email regarding
the membership fees and forms that have to be filled out! =]
Every year, this causes Trudy a severe headache and I have now given
her permission to chase down any member who hasn't responded, and hit
them as hard as she likes with a wet fish!!!!

Just to re-cap, your membership with the club is paid annually and is
£20 for those of you just wishing to train with us. (£20 to be a
member for a year, not bad eh?).
For those of you wishing to compete, the fee is more because you have
to be registered with SASA (Scottish Amateur Swimming Association) to
race. Your fee will be a total of £63.

If you haven't yet sorted your membership, please get in touch with Trudy ASAP!!



*FEES*

We are lucky enough to be in the position that we have not had to
increase the fee’s for our training sessions this year. From Feb 2016
- Jan 2017 the fee will remain at £4 per individual session or £15 per
month if you set up a standing order.
Again, any questions, just ask our committee members!



*WEBSITE/SOCIAL MEDIA*

This year we are lucky enough to have Kyran on board with us as our
‘Tech Guru’ to create a fantastic website that is eye catching and
easy to use. We’re hoping to use the website to update everyone with
events, social nights, training and more….
Check out our new site here www.perthmasters.co.uk
                  .
It’s currently being updated constantly so please keep checking it out
and any feedback is more than welcome!

We have a Twitter page….. @MastersPerth (Get following!!)

At the moment our Facebook is only a public group however keep your
eyes peeled on the new website for info on the launch of our new
Facebook page!



*Chairperson’s Channel Challenge*

How awesome does a 12 hour overnight swim sound??
Pretty exciting, yea??
Aim of the game… To be the fastest team to swim the distance of the
channel crossing and more!!!
It’s happening on the 20th Aug 2016 and I’m looking for 2 teams of 8
to take part!! More info to come!! Any questions…. Ask me!!!


*Annual Fundraiser*

Most of you will probably be aware that our annual fundraiser is
usually held near the end of the year and can result in total chaos
with everyone being busy, busy, busy in preparation for Christmas.
Its been a couple of years since we last managed to hold a summer BBQ
also, so I have this crazy idea that maybe we could combine the two
events this year?? A BBQ, which in turn, is a brilliant fundraiser and
a great day out for the whole family!! (This would mean a wee Xmas
bevy would be easier to organise and no one would have to feel bad for
not being able to make it!)
I’d love some feedback on this idea also!!


If you haven't yet fallen asleep reading this, then thank you for your time =D

Be prepared for next months edition of the ‘Chairperson’s Chinwag’
(You lot are in for a treat!!) =P haha!



Ashleigh
