= Chairperson's Chinwag - July Edition

:hp-tags:: Chairpersons Chinwag, Blog, Swimming, Perth Masters

== Hello to all of my resident water babies!! 


July is upon us!! The weather is sad and depressing but do not fear.... life in the pool is always cool!!!



Finally we have a team for The Chairperson's Channel Challenge! The lucky people who have promised to dedicate 12 hours of their lives to the salt infested waters of Gourock Open Air pool are.... Ashleigh, Erin, Rachel, Aran, Andrew, Kyran, Keiran and Michael!! Unfortunately, to become 'Legends of the Sea' we must pay a price... the cost of this years challenge is £70. That troops, works out at a whopping £8.75 each... Is everyone in the team OK to chip in for this?? More info of times to come nearer the date.....


Next on the agenda.... SASA North are holding a gala in Inverness on Sat the 20th August. I can't remember exactly what the cost for this event is but its roughly £25 for about 4 or 5 entries! Cheap as chips compared to other swimming competitions!!  Ashleigh, Andrew and Trudy plan to enter- anyone else keen and wanting to join them?? Get in touch and we'll organise sharing lifts etc.


Trying to get a club fundraiser/summer BBQ organised is proving a tad difficult!! I do believe the date I suggested in August (which appeared most popular for holding the BBQ) is the 20th Aug and unfortunately, if you've read any of the above info you'll see that this clashes with SASA North swimming gala..... As much as i think a social session with everyone is great fun, I suppose since we are a swimming club we should prioritize the swimming over the social!! I'll do some brain storming and see if I can come up with some awesome fundrasing ideas for the whole family to take part in later on in the year and I'll get some more dates out to everyone. It's looking like our summer BBQ may be more of an Autumn Adventure though!! Sorry guys!!


A wee reminder of our new website..... http://perthmasters.co.uk/
Get on and have a look!! Things are being up dated all the time!!


Finally troops... I'm going to try and enlist some help from Perth Tri Club. These guys have an underwater camera which they regularly use to do video analysis for their swimmers in the pool. I'm going to see if a couple of their coaches would come along to a few of our sessions and do some recording for any of us who would like to see our swimming from a coaches perspective- I'll let you all know when I get dates for these sessions. If you want your video analysis to take away with you you'll need to bring a USB stick with you for the coaches to transfer onto. This is a great idea for comparing your videos if we get the opportunity to do this again in the future. All videos will be delete after each session unless you bring your USB stick for saving onto.



Thanks for reading everyone!!
Reply's are very welcome!!!

