= June chairpersons Chinwag
:hp-tags: June, Blog, Chairpersons chinwag, Swimming 


== Hello to all of you!!

It's June already!! Hope everyone enjoyed the summer that we had last week ;-) Lets hope there's more good weather to follow!!

Just a wee reminder to everyone that there's a table on the notice board with 3 dates for us to hold our summer BBQ/Fundraiser. Could everyone have a wee look and put your name next to the dates that you can attend! We'll pick the date that best suits most people!! The dates are getting closer though and I still only have a couple of names up there!!

Can I double check the team for the 'Chairpersons Channel Challenge'....
It's happening on the 13th of August, we'll be leaving about 4pm (ish) on Sat to get to the pool and we will be there till about 8am on Sunday the 14th. 
Here's the list of people I have for definite swimming:

Ashleigh
Aran
Erin
Keiran
Kyran
Michael

Who else is up for it?! Please email me if yr keen, I need to get in touch with Inverclyde to confirm our team (or teams) asap!!

On the 9th - 11th of September we have the annual Inverclyde swimming competition. It's a fantastic event and this year we're looking to grab a spot in the top 3 clubs attending the competition!! Points make prizes so we need as many swimmers as possible to come along and enjoy the friendly competition and the evening prize giving and ceilidh!! Next month we'll be looking to get organised for this and get accommodation sorted, so get the dates in your diaries now :-D

I hope everyone's happy with the way the coaching is going at the moment. If anyone has any questions/issues/idea's  please drop me an email and I'll get back to you!!!

I think I've nipped your heads enough for this month... thanks for reading everyone!!

Enjoy your weekend!

Ashleigh