= Chairperson's Chinwag - August Edition

:hp-tags:: Chairpersons Chinwag, Blog, Swimming, Perth Masters

== Hello to you all!!


I understand that we're nearly a third of the way through the month and I'm just getting round to this edition of the 'Chinwag', but this has been a very busy time getting things organised for all of these up and coming Masters Swimming events!! 
(I'm sure you won't have noticed the delay right enough..... Your probably all glued to the Olympics on the TV thinking about how your swimming technique looks exactly like those that your watching!!)

;-)

Just to make sure that your definitely swimming like these olympians, I'm hoping to get a date organised this month for the underwater video analysis. Can I ask those of you who would be interested in having their video analysis done to give me a wee shout just so I have a rough idea of how long we'll need with the camera and the Tri club coaches.


A huge good luck to the 8 mad mental maniacs who have agreed to the Chairperson's Chanel Challenge! The 12 hour swimming mission starts at 7pm on Sat night and will continue all the way through to 7am on the Sunday!! I hope all you troopers have read the email sent out earlier in the week with all the info on it you need!!
(I hope coaches Erin and Roddy will be gentle with us this week! We are tapering for this Great Gourock Gathering!! =D)


More good luck is needed for our Terrific Trio; Andrew.B, Trudy and Ashleigh who have all signed up to SASA North gala up in Inverness!! This takes place on the 20th of the month and all of their entries have been accepted!! Swim fast guys!!


As you will have noticed, my attempts of having a summer family BBQ for us haven't quite gone to plan! I will however, keep my brain ticking over and I'll come up with dates and a venue for us to hopefully all get together before Christmas!!



As always, thanks for reading troops!

See you all Tuesday!!